name: Publish

on:
  push:
    branches: ['master']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4
      - run: |
          echo ${auth_token} | ko login index.docker.io --username masumi --password-stdin
          ko publish --base-import-paths ./cmd/gochip-8/
        env:
          KO_DOCKER_REPO: masumi
          auth_token: ${{ secrets.AUTH_TOKEN }}
